// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePost = "posts"

// Post 博客文章表
type Post struct {
	ID        uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title     string    `gorm:"column:title;not null;comment:文章标题" json:"title"`                              // 文章标题
	Content   string    `gorm:"column:content;not null;comment:文章内容" json:"content"`                          // 文章内容
	UserID    int32     `gorm:"column:user_id;not null;comment:关联用户 ID" json:"user_id"`                       // 关联用户 ID
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:记录创建时间" json:"created_at"` // 记录创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:记录更新时间" json:"updated_at"` // 记录更新时间
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
