// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User 用户信息表
type User struct {
	ID        uint64    `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增唯一标识" json:"id"`               // 自增唯一标识
	Username  string    `gorm:"column:username;not null;comment:用户名" json:"username"`                           // 用户名
	Password  string    `gorm:"column:password;not null;comment:密码" json:"password"`                            // 密码
	Email     string    `gorm:"column:email;not null;comment:电子邮件地址" json:"email"`                              // 电子邮件地址
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:记录创建时间" json:"created_at"`   // 记录创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:记录最后更新时间" json:"updated_at"` // 记录最后更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
