// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comments"

// Comment 文章评论表
type Comment struct {
	ID        uint64    `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增唯一标识" json:"id"`             // 自增唯一标识
	Content   string    `gorm:"column:content;not null;comment:评论内容" json:"content"`                          // 评论内容
	UserID    int32     `gorm:"column:user_id;not null;comment:用户ID，关联 users 表的 id" json:"user_id"`           // 用户ID，关联 users 表的 id
	PostID    int32     `gorm:"column:post_id;not null;comment:文章ID，关联 posts 表的 id" json:"post_id"`           // 文章ID，关联 posts 表的 id
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:评论创建时间" json:"created_at"` // 评论创建时间
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
